# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc import TraceGraphAnalysis_pb2 as grpc_dot_TraceGraphAnalysis__pb2
from trace import trace_pb2 as trace_dot_trace__pb2


class TraceGraphAnomalyAnalysisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/TraceGraphAnomalyAnalysis/SayHello',
                request_serializer=grpc_dot_TraceGraphAnalysis__pb2.Hello.SerializeToString,
                response_deserializer=grpc_dot_TraceGraphAnalysis__pb2.Hello.FromString,
                )
        self.StreamAnomalyServiceRootCauseLocalization = channel.stream_unary(
                '/TraceGraphAnomalyAnalysis/StreamAnomalyServiceRootCauseLocalization',
                request_serializer=trace_dot_trace__pb2.TraceGraph.SerializeToString,
                response_deserializer=grpc_dot_TraceGraphAnalysis__pb2.Service.FromString,
                )
        self.AnomalyServiceRootCauseLocalization = channel.unary_unary(
                '/TraceGraphAnomalyAnalysis/AnomalyServiceRootCauseLocalization',
                request_serializer=trace_dot_trace__pb2.TraceGraph.SerializeToString,
                response_deserializer=grpc_dot_TraceGraphAnalysis__pb2.Service.FromString,
                )


class TraceGraphAnomalyAnalysisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAnomalyServiceRootCauseLocalization(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnomalyServiceRootCauseLocalization(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TraceGraphAnomalyAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=grpc_dot_TraceGraphAnalysis__pb2.Hello.FromString,
                    response_serializer=grpc_dot_TraceGraphAnalysis__pb2.Hello.SerializeToString,
            ),
            'StreamAnomalyServiceRootCauseLocalization': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamAnomalyServiceRootCauseLocalization,
                    request_deserializer=trace_dot_trace__pb2.TraceGraph.FromString,
                    response_serializer=grpc_dot_TraceGraphAnalysis__pb2.Service.SerializeToString,
            ),
            'AnomalyServiceRootCauseLocalization': grpc.unary_unary_rpc_method_handler(
                    servicer.AnomalyServiceRootCauseLocalization,
                    request_deserializer=trace_dot_trace__pb2.TraceGraph.FromString,
                    response_serializer=grpc_dot_TraceGraphAnalysis__pb2.Service.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TraceGraphAnomalyAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TraceGraphAnomalyAnalysis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TraceGraphAnomalyAnalysis/SayHello',
            grpc_dot_TraceGraphAnalysis__pb2.Hello.SerializeToString,
            grpc_dot_TraceGraphAnalysis__pb2.Hello.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamAnomalyServiceRootCauseLocalization(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/TraceGraphAnomalyAnalysis/StreamAnomalyServiceRootCauseLocalization',
            trace_dot_trace__pb2.TraceGraph.SerializeToString,
            grpc_dot_TraceGraphAnalysis__pb2.Service.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnomalyServiceRootCauseLocalization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TraceGraphAnomalyAnalysis/AnomalyServiceRootCauseLocalization',
            trace_dot_trace__pb2.TraceGraph.SerializeToString,
            grpc_dot_TraceGraphAnalysis__pb2.Service.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
