# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/TraceGraphAnalysis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from trace import trace_pb2 as trace_dot_trace__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc/TraceGraphAnalysis.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dgrpc/TraceGraphAnalysis.proto\x1a\x11trace/trace.proto\"|\n\x07Service\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x16\n\x0einterface_name\x18\x02 \x01(\t\x12\x15\n\rinterface_uri\x18\x03 \x01(\t\x12\x1a\n\rinstance_uuid\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_instance_uuid\"\x1d\n\x05Hello\x12\x14\n\x0cservice_name\x18\x01 \x01(\t2\xcd\x01\n\x19TraceGraphAnomalyAnalysis\x12\x1c\n\x08SayHello\x12\x06.Hello\x1a\x06.Hello\"\x00\x12L\n)StreamAnomalyServiceRootCauseLocalization\x12\x11.trace.TraceGraph\x1a\x08.Service\"\x00(\x01\x12\x44\n#AnomalyServiceRootCauseLocalization\x12\x11.trace.TraceGraph\x1a\x08.Service\"\x00\x62\x06proto3'
  ,
  dependencies=[trace_dot_trace__pb2.DESCRIPTOR,])




_SERVICE = _descriptor.Descriptor(
  name='Service',
  full_name='Service',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='Service.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interface_name', full_name='Service.interface_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interface_uri', full_name='Service.interface_uri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_uuid', full_name='Service.instance_uuid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_instance_uuid', full_name='Service._instance_uuid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=52,
  serialized_end=176,
)


_HELLO = _descriptor.Descriptor(
  name='Hello',
  full_name='Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='Hello.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=207,
)

_SERVICE.oneofs_by_name['_instance_uuid'].fields.append(
  _SERVICE.fields_by_name['instance_uuid'])
_SERVICE.fields_by_name['instance_uuid'].containing_oneof = _SERVICE.oneofs_by_name['_instance_uuid']
DESCRIPTOR.message_types_by_name['Service'] = _SERVICE
DESCRIPTOR.message_types_by_name['Hello'] = _HELLO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Service = _reflection.GeneratedProtocolMessageType('Service', (_message.Message,), {
  'DESCRIPTOR' : _SERVICE,
  '__module__' : 'grpc.TraceGraphAnalysis_pb2'
  # @@protoc_insertion_point(class_scope:Service)
  })
_sym_db.RegisterMessage(Service)

Hello = _reflection.GeneratedProtocolMessageType('Hello', (_message.Message,), {
  'DESCRIPTOR' : _HELLO,
  '__module__' : 'grpc.TraceGraphAnalysis_pb2'
  # @@protoc_insertion_point(class_scope:Hello)
  })
_sym_db.RegisterMessage(Hello)



_TRACEGRAPHANOMALYANALYSIS = _descriptor.ServiceDescriptor(
  name='TraceGraphAnomalyAnalysis',
  full_name='TraceGraphAnomalyAnalysis',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=210,
  serialized_end=415,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='TraceGraphAnomalyAnalysis.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLO,
    output_type=_HELLO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StreamAnomalyServiceRootCauseLocalization',
    full_name='TraceGraphAnomalyAnalysis.StreamAnomalyServiceRootCauseLocalization',
    index=1,
    containing_service=None,
    input_type=trace_dot_trace__pb2._TRACEGRAPH,
    output_type=_SERVICE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AnomalyServiceRootCauseLocalization',
    full_name='TraceGraphAnomalyAnalysis.AnomalyServiceRootCauseLocalization',
    index=2,
    containing_service=None,
    input_type=trace_dot_trace__pb2._TRACEGRAPH,
    output_type=_SERVICE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRACEGRAPHANOMALYANALYSIS)

DESCRIPTOR.services_by_name['TraceGraphAnomalyAnalysis'] = _TRACEGRAPHANOMALYANALYSIS

# @@protoc_insertion_point(module_scope)
